x-clickhouse-image: &clickhouse-image clickhouse:${CLICKHOUSE_VERSION:-26.1-jammy}
x-postgres-image: &postgres-image postgres:${POSTGRES_VERSION:-18.1-alpine}

services:
  postgres:
    image: *postgres-image
    container_name: ingest-db
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'nyc_taxi'
    ports:
      - '5432:5432'
    volumes:
      - vol-tlc-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure

  clickhouse:
    image: *clickhouse-image
    container_name: clickhouse
    environment:
      CLICKHOUSE_DB: 'default'
      CLICKHOUSE_USER: 'clickhouse'
      CLICKHOUSE_PASSWORD: 'clickhouse'
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 0
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - vol-clickhouse-data:/var/lib/clickhouse/
      - vol-clickhouse-logs:/var/log/clickhouse-server/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8123/ || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: on-failure

volumes:
  vol-tlc-db:
    name: vol-tlc-db
  vol-clickhouse-data:
    name: vol-clickhouse-data
  vol-clickhouse-logs:
    name: vol-clickhouse-logs
